'use client'

import { useState, useEffect } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { CheckCircle, XCircle, AlertCircle, FileText, DollarSign, CreditCard, AlertTriangle } from 'lucide-react'

export default function ApplicationReview({ id = '123' }) {
  const [application, setApplication] = useState(null)
  const [applicationOverview, setApplicationOverview] = useState({
    shouldApprove: false,
    explanation: 'This is a brief explanation generated by ChatGPT.',
    relevantData: {
      'Income Verified': 'Yes',
      'Debt-to-Income Ratio': 'Low',
      'Credit History': 'Good',
    },
  })

  useEffect(() => {
    // Simulating API call
    setApplication({
      id,
      name: 'John Doe',
      email: 'john@example.com',
      income: '$50,000',
      creditScore: 720,
      riskScore: 75,
      documents: [
        { type: 'ID', status: 'verified' },
        { type: 'Proof of Income', status: 'pending' },
        { type: 'Bank Statement', status: 'verified' },
      ]
    })
  }, [id])

  if (!application) {
    return <div>Loading...</div>
  }

  const getRiskScoreColor = (score) => {
    if (score < 50) return 'bg-green-100 text-green-800'
    if (score < 75) return 'bg-yellow-100 text-yellow-800'
    return 'bg-red-100 text-red-800'
  }

  const getDocumentIcon = (status) => {
    switch (status) {
      case 'verified':
        return <CheckCircle className="h-5 w-5 text-green-500" />
      case 'pending':
        return <AlertCircle className="h-5 w-5 text-yellow-500" />
      default:
        return <XCircle className="h-5 w-5 text-red-500" />
    }
  }

  return (
    <div className="container mx-auto p-4 space-y-6">
      <h1 className="text-3xl font-bold">Application Review</h1>
      
      <Card>
        <CardHeader>
          <CardTitle>Applicant Information</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-6">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-sm font-medium text-muted-foreground">Full name</p>
              <p className="text-lg font-semibold">{application.name}</p>
            </div>
            <div>
              <p className="text-sm font-medium text-muted-foreground">Email address</p>
              <p className="text-lg font-semibold">{application.email}</p>
            </div>
            <div>
              <p className="text-sm font-medium text-muted-foreground">Income</p>
              <p className="text-lg font-semibold">{application.income}</p>
            </div>
            <div>
              <p className="text-sm font-medium text-muted-foreground">Credit Score</p>
              <p className="text-lg font-semibold">{application.creditScore}</p>
            </div>
          </div>
          
          <div>
            <p className="text-sm font-medium text-muted-foreground mb-2">Risk Score</p>
            <Badge variant="outline" className={getRiskScoreColor(application.riskScore)}>
              {application.riskScore}
            </Badge>
          </div>
          
          <div>
            <p className="text-sm font-medium text-muted-foreground mb-2">Documents</p>
            <ul className="space-y-2">
              {application.documents.map((document, index) => (
                <li key={index} className="flex items-center justify-between">
                  <div className="flex items-center space-x-2">
                    {getDocumentIcon(document.status)}
                    <span>{document.type}</span>
                  </div>
                  <Button variant="ghost" size="sm">View</Button>
                </li>
              ))}
            </ul>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Application Overview</CardTitle>
          <CardDescription>AI-generated summary and recommendation</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center space-x-2">
            <p className="text-sm font-medium">Should Approve:</p>
            <Badge variant={applicationOverview.shouldApprove ? "success" : "destructive"}>
              {applicationOverview.shouldApprove ? 'Yes' : 'No'}
            </Badge>
          </div>
          
          <div>
            <p className="text-sm font-medium mb-1">Explanation:</p>
            <p className="text-sm text-muted-foreground">{applicationOverview.explanation}</p>
          </div>
          
          <div>
            <p className="text-sm font-medium mb-1">Relevant Data:</p>
            <ul className="grid grid-cols-2 gap-2">
              {Object.entries(applicationOverview.relevantData).map(([key, value]) => (
                <li key={key} className="flex items-center space-x-2">
                  <Badge variant="outline">{key}</Badge>
                  <span className="text-sm">{value}</span>
                </li>
              ))}
            </ul>
          </div>
        </CardContent>
      </Card>

      <div className="flex justify-end space-x-4">
        <Button variant="destructive">
          <XCircle className="mr-2 h-4 w-4" />
          Reject
        </Button>
        <Button variant="secondary">
          <AlertTriangle className="mr-2 h-4 w-4" />
          Request More Info
        </Button>
        <Button variant="default">
          <CheckCircle className="mr-2 h-4 w-4" />
          Approve
        </Button>
      </div>
    </div>
  )
}